# Generated by Django 2.1 on 2019-06-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widower', 'Widower')], max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('on_notice', 'On Notice'), ('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('terminated', 'Terminated')], max_length=20, null=True)),
            ],
        ),
    ]
