# Generated by Django 2.2.6 on 2019-10-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
